# ==================================================
# Spring Boot 開発環境設定
# ==================================================
spring:
  # Flyway設定
  flyway:
    # 実スキーマおよび、開発検証用のモックデータのパス
    locations: classpath:db/migration,classpath:db/mock

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  # Security設定
  security:
    swagger-enabled: true
    cookie:
      secure: false
      same-site: Lax

  # ストレージ設定(MinIO)
  storage:
    # SDK接続先エンドポイント
    endpoint: ${STORAGE_ENDPOINT:}
    # ストレージ接続用のアクセスキー
    access-key: ${STORAGE_ACCESS_KEY}
    # ストレージ接続用のシークレットキー
    secret-key: ${STORAGE_SECRET_KEY}
    # パススタイルアクセスを使用するか
    path-style-access: true
