# ==================================================
# Spring Boot 開発環境設定
# ==================================================
spring:
  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: validate
    show-sql: true

logging:
  level:
    root: INFO
    "[com.pitvia]": DEBUG
